# Docker Compose configuration for Claude Flow development environment

services:
  claude-flow:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-22}
        PACKAGE_MANAGER: ${PACKAGE_MANAGER:-pnpm}
        CLAUDE_FLOW_VERSION: ${CLAUDE_FLOW_VERSION:-alpha}
        USER_UID: ${USER_UID:-1001}
        USER_GID: ${USER_GID:-1001}
        EXTRA_PACKAGES: ${EXTRA_PACKAGES:-}
    image: ${PROJECT_NAME:-myproject}-claude-flow:latest
    container_name: ${PROJECT_NAME:-myproject}-claude-flow
    volumes:
      # Project directory - adjust path as needed
      - ${PROJECT_PATH:-.}:/app:rw
      # Docker socket for container operations (optional)
      - /var/run/docker.sock:/var/run/docker.sock
      # Separate volume for node_modules for better performance
      - node_modules:/app/node_modules
      # Cache directories
      - pnpm_store:/app/.pnpm-store
      - npm_cache:/root/.npm
    environment:
      # API Keys - NOT NEEDED! Claude Flow uses Claude Code CLI auth
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Development environment
      - NODE_ENV=${NODE_ENV:-development}
      # Deno configuration
      - DENO_INSTALL=/root/.deno
      - PATH=/root/.deno/bin:${PATH}
      # Package manager
      - PACKAGE_MANAGER=${PACKAGE_MANAGER:-pnpm}
      # Custom environment variables
      - CUSTOM_ENV_1=${CUSTOM_ENV_1:-}
      - CUSTOM_ENV_2=${CUSTOM_ENV_2:-}
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      # Vite dev server
      - "${VITE_PORT:-5173}:5173"
      # Vite preview
      - "${PREVIEW_PORT:-4173}:4173"
      # Claude Flow UI
      - "${CLAUDE_FLOW_PORT:-3000}:3000"
      # Alternative ports
      - "${ALT_PORT_1:-8080}:8080"
      - "${ALT_PORT_2:-3001}:3001"
      # Add more ports as needed
    networks:
      - claude-network
    restart: unless-stopped
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-2}'
          memory: ${MEMORY_LIMIT:-4G}
        reservations:
          cpus: '${CPU_RESERVATION:-0.5}'
          memory: ${MEMORY_RESERVATION:-512M}


networks:
  claude-network:
    driver: bridge
    name: ${PROJECT_NAME:-myproject}_network

volumes:
  # Named volumes with project prefix for isolation
  node_modules:
    name: ${PROJECT_NAME:-myproject}_node_modules
  pnpm_store:
    name: ${PROJECT_NAME:-myproject}_pnpm_store
  npm_cache:
    name: ${PROJECT_NAME:-myproject}_npm_cache